name = "rust"
title = "Rust Driver"

intersphinx = [ "https://www.mongodb.com/docs/manual/objects.inv",
                "https://www.mongodb.com/docs/atlas/objects.inv"
              ]

# toc_landing_pages = ["/paths/to/pages/that/have/nested/content"]

sharedinclude_root = "https://raw.githubusercontent.com/10gen/docs-shared/main/"

# [constants]
# constant = "value"
